import { Fira_Code } from "next/font/google";
import "./globals.css";

const fira_code = Fira_Code({ subsets: ["latin"] });

export const metadata = {
  title: "Aditya Gupta",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={fira_code.className}>{children}</body>
    </html>
  );
}
